export const keywordsMaker = array => {
    let tempArray = ['']
    for (let i = 0; i < array.length; i++) {
        for(let j = 1; j < array[i].length + 1; j++) {
            tempArray.push(array[i].slice(0, j).toLowerCase())
        }
    }
    return tempArray
}

export const messageSorter = (array1, array2) => {
    const tempArray = []
    let array1Pointer = 0
    let array2Pointer = 0
    while ((array1Pointer) !== array1.length && (array2Pointer) !== array2.length) {
        if( array1[array1Pointer].value.lastMessageTime > array2[array2Pointer].value.lastMessageTime) {
            tempArray.push(array1[array1Pointer])
            array1Pointer += 1
        } else {
            tempArray.push(array2[array2Pointer])
            array2Pointer += 1
        }
    }
    if (array1.length === array1Pointer) {
        for (let i = array2Pointer; i < array2.length; i++) {
            tempArray.push(array2[i])
        }
    } else {
        for (let i = array1Pointer; i < array1.length; i++) {
            tempArray.push(array1[i])
        }
    }
    return tempArray
}


export const mrtStations = [
    { title: 'Admiralty' },
    { title: 'Aljunied' },
    { title: 'Ang Mo Kio' },
    { title: 'Bartley' },
    { title: 'Beauty World' },
    { title: 'Bedok' },
    { title: 'Bedok North' },
    { title: 'Bedok Reservoir' },
    { title: 'Bencoolen' },
    { title: 'Bendemeer' },
    { title: 'Bishan' },
    { title: 'Boon Keng' },
    { title: 'Boon Lay' },
    { title: 'Botanic Gardens' },
    { title: 'Bouna Vista' },
    { title: 'Braddel' },
    { title: 'Bras Basah' },
    { title: 'Buangkok' },
    { title: 'Bugis' },
    { title: 'Bukit Batok' },
    { title: 'Bukit Brown' },
    { title: 'Bukit Gombak' },
    { title: 'Bukit Panjang' },
    { title: 'Caldecott' },
    { title: 'Canberra' },
    { title: 'Cashew' },
    { title: 'Changi Airport' },
    { title: 'Chinatown' },
    { title: 'Chinese Garden' },
    { title: 'Choa Chu Kang' },
    { title: 'City Hall' },
    { title: 'Clarke Quay' },
    { title: 'Clementi' },
    { title: 'Commonwealth' },
    { title: 'Dakota' },
    { title: 'Dhoby Ghaut' },
    { title: 'Dover' },
    { title: 'Downtown' },
    { title: 'Esplanade' },
    { title: 'Eunos' },
    { title: 'Expo' },
    { title: 'Farrer Park' },
    { title: 'Farrer Road' },
    { title: 'Fort Canning' },
    { title: 'Geylang Bahru' },
    { title: 'Gul Circle' },
    { title: 'HarbourFront' },
    { title: 'Haw Par Villa' },
    { title: 'Hillview' },
    { title: 'Holland Village' },
    { title: 'Hougang' },
    { title: 'Hume' },
    { title: 'Jalan Besar' },
    { title: 'Joo Koon' },
    { title: 'Jurong East' },
    { title: 'Kaki Bukit' },
    { title: 'Kallang' },
    { title: 'Kembangan' },
    { title: 'Kent Ridge' },
    { title: 'Khatib' },
    { title: 'King Albert Park' },
    { title: 'Kovan' },
    { title: 'Kranji' },
    { title: 'Labrador Park' },
    { title: 'Lakeside' },
    { title: 'Lavender' },
    { title: 'Little India' },
    { title: 'Lorong Chuan' },
    { title: 'MacPherson' },
    { title: 'Marina Bay' },
    { title: 'Marina South Pier' },
    { title: 'Marsiling' },
    { title: 'Marymount' },
    { title: 'Mattar' },
    { title: 'Mountbatten' },
    { title: 'Newton' },
    { title: 'Nicoll Highway' },
    { title: 'Novena' },
    { title: 'Orchard' },
    { title: 'Outram Park' },
    { title: 'Pasir Panjang' },
    { title: 'Pasir Ris' },
    { title: 'Paya Lebar' },
    { title: 'Pioneer' },
    { title: 'Potong Pasir' },
    { title: 'Promenade' },
    { title: 'Punggol' },
    { title: 'Queenstown' },
    { title: 'Raffles Place' },
    { title: 'Redhill' },
    { title: 'Rochor' },
    { title: 'Sembawang' },
    { title: 'Sengkang' },
    { title: 'Serangoon' },
    { title: 'Simei' },
    { title: 'Sixth Avenue' },
    { title: 'Somerset' },
    { title: 'Stadium' },
    { title: 'Stevens' },
    { title: 'Tai Seng' },
    { title: 'Tampines' },
    { title: 'Tampines East' },
    { title: 'Tampines West' },
    { title: 'Tan Kah Kee' },
    { title: 'Tanah Merah' },
    { title: 'Tanjong Pagar' },
    { title: 'Telok Ayer' },
    { title: 'Telok Blangah' },
    { title: 'Tiong Bahru' },
    { title: 'Toa Payoh' },
    { title: 'Tuas Crescent' },
    { title: 'Tuas Link' },
    { title: 'Tuas West Road' },
    { title: 'Ubi' },
    { title: 'Upper Changi' },
    { title: 'Woodlands' },
    { title: 'Woodleigh' },
    { title: 'Yew Tee' },
    { title: 'Yio Chu kang' },
    { title: 'Yishun' },
    { title: 'one-north' }
]
// const zones = []
//
// const sorter  = array => {
//     let counter = 1
//     let temp = array
//     while (temp.length !== 0) {
//         let smallest = temp[0]
//         for(let i = 1; i< temp.length; i++) {
//             if (smallest >  temp[i]) {
//                 smallest = temp[i]
//             }
//         }
//         temp = temp.filter(item => item !== smallest)
//         zones.push({title: smallest})
//         console.log({title: smallest})
//     }
// }
//
// sorter([
//     'Jurong East',
//     'Bukit Batok',
//     'Bukit Gombak',
//     'Choa Chu Kang',
//     'Yew Tee',
//     'Kranji',
//     'Marsiling',
//     'Woodlands',
//     'Admiralty',
//     'Sembawang',
//     'Canberra',
//     'Yishun',
//     'Khatib',
//     'Yio Chu kang',
//     'Ang Mo Kio',
//     'Bishan',
//     'Braddel',
//     'Toa Payoh',
//     'Novena',
//     'Newton',
//     'Orchard',
//     'Somerset',
//     'Dhoby Ghaut',
//     'City Hall',
//     'Raffles Place',
//     'Marina Bay',
//     'Marina South Pier',
//     'Pasir Ris',
//     'Tampines',
//     'Simei',
//     'Tanah Merah',
//     'Bedok',
//     'Kembangan',
//     'Eunos',
//     'Paya Lebar',
//     'Aljunied',
//     'Kallang',
//     'Lavender',
//     'Bugis',
//     'Tanjong Pagar',
//     'Outram Park',
//     'Tiong Bahru',
//     'Redhill',
//     'Queenstown',
//     'Commonwealth',
//     'Bouna Vista',
//     'Dover',
//     'Clementi',
//     'Jurong East',
//     'Chinese Garden',
//     'Lakeside',
//     'Boon Lay',
//     'Pioneer',
//     'Joo Koon',
//     'Gul Circle',
//     'Tuas Crescent',
//     'Tuas West Road',
//     'Tuas Link',
//     'Tanah Merah',
//     'Expo',
//     'Changi Airport',
//     'HarbourFront',
//     'Outram Park',
//     'Chinatown',
//     'Clarke Quay',
//     'Woodleigh',
//     'Little India',
//     'Farrer Park',
//     'Boon Keng',
//     'Potong Pasir',
//     'Serangoon',
//     'Kovan',
//     'Hougang',
//     'Buangkok',
//     'Sengkang',
//     'Punggol',
//     'Bras Basah',
//     'Esplanade',
//     'Promenade',
//     'Nicoll Highway',
//     'Stadium',
//     'Mountbatten',
//     'Dakota',
//     'MacPherson',
//     'Tai Seng',
//     'Bartley',
//     'Marymount',
//     'Lorong Chuan',
//     'Caldecott',
//     'Bukit Brown',
//     'Botanic Gardens',
//     'Farrer Road',
//     'Holland Village',
//     'Bouna Vista',
//     'one-north',
//     'Kent Ridge',
//     'Haw Par Villa',
//     'Pasir Panjang',
//     'Labrador Park',
//     'Telok Blangah',
//     'Bukit Panjang',
//     'Cashew',
//     'Hillview',
//     'Hume',
//     'Beauty World',
//     'King Albert Park',
//     'Sixth Avenue',
//     'Tan Kah Kee',
//     'Rochor',
//     'Stevens',
//     'Downtown',
//     'Telok Ayer',
//     'Fort Canning',
//     'Bencoolen',
//     'Jalan Besar',
//     'Bendemeer',
//     'Geylang Bahru',
//     'Mattar',
//     'MacPherson',
//     'Ubi',
//     'Kaki Bukit',
//     'Bedok North',
//     'Bedok Reservoir',
//     'Tampines West',
//     'Tampines East',
//     'Upper Changi',
// ])
