export const keywordsMaker = array => {
    let tempArray = ['']
    for (let i = 0; i < array.length; i++) {
        for(let j = 1; j < array[i].length + 1; j++) {
            tempArray.push(array[i].slice(0, j).toLowerCase())
        }
    }
    return tempArray
}

export const messageSorter = (array1, array2) => {
    const tempArray = []
    let array1Pointer = 0
    let array2Pointer = 0
    while ((array1Pointer) !== array1.length && (array2Pointer) !== array2.length) {
        if( array1[array1Pointer].value.lastMessageTime > array2[array2Pointer].value.lastMessageTime) {
            tempArray.push(array1[array1Pointer])
            array1Pointer += 1
        } else {
            tempArray.push(array2[array2Pointer])
            array2Pointer += 1
        }
    }
    if (array1.length === array1Pointer) {
        for (let i = array2Pointer; i < array2.length; i++) {
            tempArray.push(array2[i])
        }
    } else {
        for (let i = array1Pointer; i < array1.length; i++) {
            tempArray.push(array1[i])
        }
    }
    return tempArray
}

export const zones = [
    {id: 1, name: 'Ang Mo Kio'},
    {id: 2, name: 'Bedok'},
    {id: 3, name: 'Bishan'},
    {id: 4, name: 'Boon Lay'},
    {id: 5, name: 'Bukit Batok'},
    {id: 6, name: 'Bukit Merah'},
    {id: 7, name: 'Bukit Panjang'},
    {id: 8, name: 'Bukit Timah'},
    {id: 9, name: 'Changi'},
    {id: 10, name: 'Changi Bay'},
    {id: 11, name: 'Choa Chu Kang'},
    {id: 12, name: 'Clementi'},
    {id: 13, name: 'Downtown Core'},
    {id: 14, name: 'Geylang'},
    {id: 15, name: 'Hougang'},
    {id: 16, name: 'Jurong East'},
    {id: 17, name: 'Jurong West'},
    {id: 18, name: 'Kallang'},
    {id: 19, name: 'Lim Chu Kang'},
    {id: 20, name: 'Mandai'},
    {id: 21, name: 'Marina East'},
    {id: 22, name: 'Marina South'},
    {id: 23, name: 'Marine Parade'},
    {id: 24, name: 'Museum'},
    {id: 25, name: 'Newton'},
    {id: 26, name: 'Novena'},
    {id: 27, name: 'Orchard'},
    {id: 28, name: 'Outram'},
    {id: 29, name: 'Pasir Ris'},
    {id: 30, name: 'Paya Lebar'},
    {id: 31, name: 'Pioneer'},
    {id: 32, name: 'Punggol'},
    {id: 33, name: 'Queenstown'},
    {id: 34, name: 'River Valley'},
    {id: 35, name: 'Rochor'},
    {id: 36, name: 'Seletar'},
    {id: 37, name: 'Sembawang'},
    {id: 38, name: 'Sengkang'},
    {id: 39, name: 'Serangoon'},
    {id: 40, name: 'Simpang'},
    {id: 41, name: 'Singapore River'},
    {id: 42, name: 'Straits View'},
    {id: 43, name: 'Sungei Kadut'},
    {id: 44, name: 'Tampines'},
    {id: 45, name: 'Tanglin'},
    {id: 46, name: 'Tengah'},
    {id: 47, name: 'Toa Payoh'},
    {id: 48, name: 'Tuas'},
    {id: 49, name: 'Woodlands'},
    {id: 50, name: 'Yishun'},
]

export const mrtStations = [
    { id: 1, name: 'Admiralty' },
    { id: 2, name: 'Aljunied' },
    { id: 3, name: 'Ang Mo Kio' },
    { id: 4, name: 'Bartley' },
    { id: 5, name: 'Beauty World' },
    { id: 6, name: 'Bedok' },
    { id: 7, name: 'Bedok North' },
    { id: 8, name: 'Bedok Reservoir' },
    { id: 9, name: 'Bencoolen' },
    { id: 10, name: 'Bendemeer' },
    { id: 11, name: 'Bishan' },
    { id: 12, name: 'Boon Keng' },
    { id: 13, name: 'Boon Lay' },
    { id: 14, name: 'Botanic Gardens' },
    { id: 15, name: 'Bouna Vista' },
    { id: 16, name: 'Braddel' },
    { id: 17, name: 'Bras Basah' },
    { id: 18, name: 'Buangkok' },
    { id: 19, name: 'Bugis' },
    { id: 20, name: 'Bukit Batok' },
    { id: 21, name: 'Bukit Brown' },
    { id: 22, name: 'Bukit Gombak' },
    { id: 23, name: 'Bukit Panjang' },
    { id: 24, name: 'Caldecott' },
    { id: 25, name: 'Canberra' },
    { id: 26, name: 'Cashew' },
    { id: 27, name: 'Changi Airport' },
    { id: 28, name: 'Chinatown' },
    { id: 29, name: 'Chinese Garden' },
    { id: 30, name: 'Choa Chu Kang' },
    { id: 31, name: 'City Hall' },
    { id: 32, name: 'Clarke Quay' },
    { id: 33, name: 'Clementi' },
    { id: 34, name: 'Commonwealth' },
    { id: 35, name: 'Dakota' },
    { id: 36, name: 'Dhoby Ghaut' },
    { id: 37, name: 'Dover' },
    { id: 38, name: 'Downtown' },
    { id: 39, name: 'Esplanade' },
    { id: 40, name: 'Eunos' },
    { id: 41, name: 'Expo' },
    { id: 42, name: 'Farrer Park' },
    { id: 43, name: 'Farrer Road' },
    { id: 44, name: 'Fort Canning' },
    { id: 45, name: 'Geylang Bahru' },
    { id: 46, name: 'Gul Circle' },
    { id: 47, name: 'HarbourFront' },
    { id: 48, name: 'Haw Par Villa' },
    { id: 49, name: 'Hillview' },
    { id: 50, name: 'Holland Village' },
    { id: 51, name: 'Hougang' },
    { id: 52, name: 'Hume' },
    { id: 53, name: 'Jalan Besar' },
    { id: 54, name: 'Joo Koon' },
    { id: 55, name: 'Jurong East' },
    { id: 56, name: 'Kaki Bukit' },
    { id: 57, name: 'Kallang' },
    { id: 58, name: 'Kembangan' },
    { id: 59, name: 'Kent Ridge' },
    { id: 60, name: 'Khatib' },
    { id: 61, name: 'King Albert Park' },
    { id: 62, name: 'Kovan' },
    { id: 63, name: 'Kranji' },
    { id: 64, name: 'Labrador Park' },
    { id: 65, name: 'Lakeside' },
    { id: 66, name: 'Lavender' },
    { id: 67, name: 'Little India' },
    { id: 68, name: 'Lorong Chuan' },
    { id: 69, name: 'MacPherson' },
    { id: 70, name: 'Marina Bay' },
    { id: 71, name: 'Marina South Pier' },
    { id: 72, name: 'Marsiling' },
    { id: 73, name: 'Marymount' },
    { id: 74, name: 'Mattar' },
    { id: 75, name: 'Mountbatten' },
    { id: 76, name: 'Newton' },
    { id: 77, name: 'Nicoll Highway' },
    { id: 78, name: 'Novena' },
    { id: 79, name: 'Orchard' },
    { id: 80, name: 'Outram Park' },
    { id: 81, name: 'Pasir Panjang' },
    { id: 82, name: 'Pasir Ris' },
    { id: 83, name: 'Paya Lebar' },
    { id: 84, name: 'Pioneer' },
    { id: 85, name: 'Potong Pasir' },
    { id: 86, name: 'Promenade' },
    { id: 87, name: 'Punggol' },
    { id: 88, name: 'Queenstown' },
    { id: 89, name: 'Raffles Place' },
    { id: 90, name: 'Redhill' },
    { id: 91, name: 'Rochor' },
    { id: 92, name: 'Sembawang' },
    { id: 93, name: 'Sengkang' },
    { id: 94, name: 'Serangoon' },
    { id: 95, name: 'Simei' },
    { id: 96, name: 'Sixth Avenue' },
    { id: 97, name: 'Somerset' },
    { id: 98, name: 'Stadium' },
    { id: 99, name: 'Stevens' },
    { id: 100, name: 'Tai Seng' },
    { id: 101, name: 'Tampines' },
    { id: 102, name: 'Tampines East' },
    { id: 103, name: 'Tampines West' },
    { id: 104, name: 'Tan Kah Kee' },
    { id: 105, name: 'Tanah Merah' },
    { id: 106, name: 'Tanjong Pagar' },
    { id: 107, name: 'Telok Ayer' },
    { id: 108, name: 'Telok Blangah' },
    { id: 109, name: 'Tiong Bahru' },
    { id: 110, name: 'Toa Payoh' },
    { id: 111, name: 'Tuas Crescent' },
    { id: 112, name: 'Tuas Link' },
    { id: 113, name: 'Tuas West Road' },
    { id: 114, name: 'Ubi' },
    { id: 115, name: 'Upper Changi' },
    { id: 116, name: 'Woodlands' },
    { id: 117, name: 'Woodleigh' },
    { id: 118, name: 'Yew Tee' },
    { id: 119, name: 'Yio Chu kang' },
    { id: 120, name: 'Yishun' },
    { id: 121, name: 'one-north' },
]

// const zones = []
//
// const sorter  = array => {
//     let counter = 1
//     let temp = array
//     while (temp.length !== 0) {
//         let smallest = temp[0]
//         for(let i = 1; i< temp.length; i++) {
//             if (smallest >  temp[i]) {
//                 smallest = temp[i]
//             }
//         }
//         temp = temp.filter(item => item !== smallest)
//         zones.push({id: counter, name: smallest})
//         console.log({id: counter, name: smallest})
//         counter++
//     }
// }
//
// sorter([
//     'Jurong East',
//     'Bukit Batok',
//     'Bukit Gombak',
//     'Choa Chu Kang',
//     'Yew Tee',
//     'Kranji',
//     'Marsiling',
//     'Woodlands',
//     'Admiralty',
//     'Sembawang',
//     'Canberra',
//     'Yishun',
//     'Khatib',
//     'Yio Chu kang',
//     'Ang Mo Kio',
//     'Bishan',
//     'Braddel',
//     'Toa Payoh',
//     'Novena',
//     'Newton',
//     'Orchard',
//     'Somerset',
//     'Dhoby Ghaut',
//     'City Hall',
//     'Raffles Place',
//     'Marina Bay',
//     'Marina South Pier',
//     'Pasir Ris',
//     'Tampines',
//     'Simei',
//     'Tanah Merah',
//     'Bedok',
//     'Kembangan',
//     'Eunos',
//     'Paya Lebar',
//     'Aljunied',
//     'Kallang',
//     'Lavender',
//     'Bugis',
//     'Tanjong Pagar',
//     'Outram Park',
//     'Tiong Bahru',
//     'Redhill',
//     'Queenstown',
//     'Commonwealth',
//     'Bouna Vista',
//     'Dover',
//     'Clementi',
//     'Jurong East',
//     'Chinese Garden',
//     'Lakeside',
//     'Boon Lay',
//     'Pioneer',
//     'Joo Koon',
//     'Gul Circle',
//     'Tuas Crescent',
//     'Tuas West Road',
//     'Tuas Link',
//     'Tanah Merah',
//     'Expo',
//     'Changi Airport',
//     'HarbourFront',
//     'Outram Park',
//     'Chinatown',
//     'Clarke Quay',
//     'Woodleigh',
//     'Little India',
//     'Farrer Park',
//     'Boon Keng',
//     'Potong Pasir',
//     'Serangoon',
//     'Kovan',
//     'Hougang',
//     'Buangkok',
//     'Sengkang',
//     'Punggol',
//     'Bras Basah',
//     'Esplanade',
//     'Promenade',
//     'Nicoll Highway',
//     'Stadium',
//     'Mountbatten',
//     'Dakota',
//     'MacPherson',
//     'Tai Seng',
//     'Bartley',
//     'Marymount',
//     'Lorong Chuan',
//     'Caldecott',
//     'Bukit Brown',
//     'Botanic Gardens',
//     'Farrer Road',
//     'Holland Village',
//     'Bouna Vista',
//     'one-north',
//     'Kent Ridge',
//     'Haw Par Villa',
//     'Pasir Panjang',
//     'Labrador Park',
//     'Telok Blangah',
//     'Bukit Panjang',
//     'Cashew',
//     'Hillview',
//     'Hume',
//     'Beauty World',
//     'King Albert Park',
//     'Sixth Avenue',
//     'Tan Kah Kee',
//     'Rochor',
//     'Stevens',
//     'Downtown',
//     'Telok Ayer',
//     'Fort Canning',
//     'Bencoolen',
//     'Jalan Besar',
//     'Bendemeer',
//     'Geylang Bahru',
//     'Mattar',
//     'MacPherson',
//     'Ubi',
//     'Kaki Bukit',
//     'Bedok North',
//     'Bedok Reservoir',
//     'Tampines West',
//     'Tampines East',
//     'Upper Changi',
// ])
